#!/usr/bin/env bash
set -e

if [[ "$(git rev-parse --abbrev-ref HEAD)" = "master" ]]; then
  echo
  echo "$(tput setaf 1)Oof, you were about to commit to master, luckily we have this pre-commit hook!$(tput sgr 0)"
  echo
  exit 1
fi
if [[ "$(git rev-parse --abbrev-ref HEAD)" = "main" ]]; then
  echo
  echo "$(tput setaf 1)Oof, you were about to commit to master, luckily we have this pre-commit hook!$(tput sgr 0)"
  echo
  exit 1
fi
